import { Exam, Subject, Topic, Question } from '@/types/database';

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Bihar STET',
    slug: 'bihar-stet',
    description: 'Bihar Secondary Teachers Eligibility Test for High School & Higher Secondary Teachers',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    name: 'CTET (Central Teacher Eligibility Test)',
    slug: 'ctet',
    description: 'National level teacher qualification exam',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    name: 'SSC CGL',
    slug: 'ssc-cgl',
    description: 'Staff Selection Commission Combined Graduate Level Exam',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'Computer Science',
    slug: 'computer-science',
    description: 'Core Computer Science including OS, DBMS, Data Structures, Networks',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a23',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    name: 'General Teaching Aptitude & Reasoning',
    slug: 'teaching-aptitude',
    description: 'Pedagogy, General Knowledge, and Reasoning Ability',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_TOPICS: Topic[] = [
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a31',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'Computer Fundamentals',
    slug: 'computer-fundamentals',
    description: 'CPU Architecture, Logic Gates, Number Systems',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a32',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'Operating Systems',
    slug: 'operating-systems',
    description: 'Processes, CPU Scheduling, Deadlocks, Memory Virtualization',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'DBMS',
    slug: 'dbms',
    description: 'Relational Model, Normalization, SQL, Transactions',
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a34',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'Data Structures',
    slug: 'data-structures',
    description: 'Trees, Graphs, Sorting, Hash Tables',
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a35',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    name: 'Software Engineering',
    slug: 'software-engineering',
    description: 'SDLC, Agile, UML Modeling, System Testing',
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a41',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    topic_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a32',
    question_type: 'single_select',
    question_text: 'Which of the following CPU scheduling algorithms may cause starvation for low-priority processes?',
    question_image_path: null,
    options: [
      { text: 'First-Come First-Served (FCFS)', image_path: null },
      { text: 'Round Robin (RR)', image_path: null },
      { text: 'Shortest Job First (SJF) / Priority Scheduling', image_path: null },
      { text: 'First In First Out (FIFO)', image_path: null },
    ],
    correct_option: 3,
    explanation: 'Priority Scheduling and Shortest Job First (SJF) can lead to starvation (indefinite blocking) where low priority or long CPU burst processes may never execute if higher priority jobs keep arriving. Aging solves this issue.',
    difficulty: 'medium',
    default_time_seconds: 45,
    marks: 1,
    negative_marks: 0.25,
    source_name: 'Bihar STET',
    source_year: 2024,
    status: 'published',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a42',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    topic_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a35',
    question_type: 'single_select',
    question_text: 'Study the following diagram and identify which behavioral UML diagrams represent dynamic system workflows.',
    question_image_path: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format&fit=crop&q=80',
    options: [
      { text: 'Activity diagram', image_path: null },
      { text: 'State machine diagram', image_path: null },
      { text: 'Both (A) and (B)', image_path: null },
      { text: 'More than one of the above', image_path: null },
      { text: 'None of the above', image_path: null },
    ],
    correct_option: 3,
    explanation: 'Both Activity diagrams and State Machine diagrams are UML behavioral diagrams used to model dynamic workflows and state transitions in software systems.',
    difficulty: 'hard',
    default_time_seconds: 60,
    marks: 1,
    negative_marks: 0.25,
    source_name: 'Bihar STET',
    source_year: 2024,
    status: 'published',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a43',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    topic_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a31',
    question_type: 'single_select',
    question_text: 'Which of the following logic gate symbols produces an output of HIGH (1) only when all its inputs are HIGH (1)?',
    question_image_path: null,
    options: [
      { text: 'AND Gate', image_path: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80' },
      { text: 'OR Gate', image_path: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80' },
      { text: 'NAND Gate', image_path: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80' },
      { text: 'XOR Gate', image_path: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80' },
    ],
    correct_option: 1,
    explanation: 'An AND gate outputs 1 (True) if and only if all of its inputs are 1 (True).',
    difficulty: 'easy',
    default_time_seconds: 30,
    marks: 1,
    negative_marks: 0.25,
    source_name: 'Bihar STET',
    source_year: 2023,
    status: 'published',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    topic_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a34',
    question_type: 'single_select',
    question_text: 'Which of the following represents a balanced Binary Search Tree (AVL tree) where the balance factor of every node is in {-1, 0, +1}?',
    question_image_path: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    options: [
      { text: 'Tree configuration A (Skewed Left)', image_path: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=400&auto=format&fit=crop&q=80' },
      { text: 'Tree configuration B (AVL Balanced)', image_path: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=400&auto=format&fit=crop&q=80' },
      { text: 'Tree configuration C (Degenerate)', image_path: null },
      { text: 'All of the above', image_path: null },
    ],
    correct_option: 2,
    explanation: 'In an AVL Tree, for every node the height difference between the left and right subtrees must not exceed 1.',
    difficulty: 'medium',
    default_time_seconds: 45,
    marks: 1,
    negative_marks: 0.25,
    source_name: 'Bihar STET',
    source_year: 2024,
    status: 'published',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a45',
    exam_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    subject_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    topic_id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    question_type: 'single_select',
    question_text: 'Which normal form eliminates transitive functional dependency in relational database design?',
    question_image_path: null,
    options: [
      { text: 'First Normal Form (1NF)', image_path: null },
      { text: 'Second Normal Form (2NF)', image_path: null },
      { text: 'Third Normal Form (3NF)', image_path: null },
      { text: 'Boyce-Codd Normal Form (BCNF)', image_path: null },
      { text: 'None of the above', image_path: null },
    ],
    correct_option: 3,
    explanation: 'Third Normal Form (3NF) requires a relation to be in 2NF and have no transitive dependencies of non-prime attributes on candidate keys.',
    difficulty: 'easy',
    default_time_seconds: 30,
    marks: 1,
    negative_marks: 0.25,
    source_name: 'Bihar STET',
    source_year: 2024,
    status: 'published',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
